// <auto-generated />
using KaohsiungLightRail.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KaohsiungLightRail.Migrations
{
    [DbContext(typeof(RailDbContext))]
    partial class RailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KaohsiungLightRail.Models.LightRailData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AvgDailyFareAdjustment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgDailyGroupTicket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgDailyManualTicket")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgDailyOnBoardCard")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgDailyPlatformCard")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AvgDailyQRCode")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AvgDailyRidership")
                        .HasColumnType("int");

                    b.Property<decimal?>("AvgDailyTicketMachine")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AvgHolidayRidership")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seq")
                        .HasColumnType("int");

                    b.Property<int?>("TotalRidership")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LightRailStats");
                });
#pragma warning restore 612, 618
        }
    }
}
